# Created using wingetcreate 1.5.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: WolfVisionGmbH.vSolutionAppbyWolfVision
PackageVersion: 2.2.0.3
InstallerLocale: en-US
InstallerType: wix
ProductCode: '{6421A203-5DB6-4E7A-B683-BDA06BB16D10}'
Installers:
- InstallerUrl: https://downloads.wolfvision.com/vSolutionAppSetup_x64.msi
  Architecture: x86
  InstallerSha256: 508F8775AE9D99F6968520E68B1D5C9A1B208676421EC29744E065474F7AA57D
ManifestType: installer
ManifestVersion: 1.5.0
